name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check dependency duplications
        uses: vazco/open-standards/actions/npm-dependency-duplications/@master

      - name: Check dependency vulnerabilities
        uses: vazco/open-standards/actions/npm-dependency-vulnerabilities/@master

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Meteor
        run: npm install -g meteor

      - name: Update PATH
        run: echo "$HOME/.meteor" >> $GITHUB_PATH

      - name: Install dependencies
        run: meteor npm ci

      - name: Lint
        run: meteor npm run lint:ts

      - name: Run tests
        run: meteor npm run test:CI
